apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform
  labels:
    app: platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: platform
  template:
    metadata:
      labels:
        app: platform
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: platform
          image: project20registry.azurecr.io/platform-service:v1
          ports:
            - containerPort: 8086
          env:
            - name: SERVER_ADDRESS
              value: "0.0.0.0"
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka.default.svc.cluster.local:9092
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8086
            initialDelaySeconds: 30
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8086
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5